In [1]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [13]:
import numpy as np
n = np.arange(27)

In [14]:
type (n)

numpy.ndarray

In [15]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [11]:
l = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
    

In [12]:
print (l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]


In [17]:
n.reshape(3,3,3) 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
m = np.asarray([[123,12,123,12,33],[],[]])
m

C:\Users\0x5nc\AppData\Local\Temp/ipykernel_39752/1014715356.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m = np.asarray([[123,12,123,12,33],[],[]])


array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [22]:
import cv2
img = cv2.imread("smallgray.png", 0)

In [23]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [21]:
print (img)

None


In [24]:
cv2.imwrite("newsmallgray.png", img)

True

In [25]:
img[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [26]:
img.shape

(3, 5)

In [27]:
img[2,4]

182

In [32]:
for i in range(img.shape[0]) : 
    for j in range(img.shape[1]) :
        print (img[i,j])

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [37]:
for i in img.flat : 
    print (i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [38]:
for i in img.T :
    print (i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [42]:
ims = np.hstack((img,img,img))

In [43]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [44]:
imv = np.vstack((img,img))
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [45]:
lst = np.hsplit(ims,3)

In [46]:
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [47]:
type(lst)

list

In [48]:
print (ims )

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [50]:
lvt = np.vsplit(ims,3)

In [51]:
print ( lvt)

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)]
